import { environment } from '../../../environments/environment';

export const UrlProvider = {
  baseUrl: environment.baseUrl,
  socketBaseUrl: environment.socketBaseUrl,
  login: '/v1/auth/sign-in',
  user: '/v1/auth/user',
  register: '/v1/auth/register',
  logout: '/v1/auth/log-out',
  refresh: '/v1/auth/refresh',
  getAvailableTables: '/v1/table/available/${date}',
  getBookingsByDate: '/v1/booking/active/${date}',
  getAvailableHours: '/v1/booking/available-hours',
  createBooking: '/v1/booking',
  updateBookingStatus: '/v1/booking/status/${bookingId}',
  getBooking: '/v1/booking/get/${bookingId}',
  getUserBookings: '/v1/booking/my-bookings',
  joinBooking: '/v1/booking/join',
  getAllMenus: '/v1/menu/all',
  getAllAvailableMenus: '/v1/menu/available',
  getMenu: '/v1/menu/info/${menuId}',
  postOrder: '/v1/order/create/${bookingId}',
  getOrdersByBookingId: '/v1/order/booking/${bookingId}',
  getOrdersByDate: '/v1/order/date/${date}',
  updateOrderStatus: '/v1/order/update-status',
  subscribeToNotifications: '/v1/notifications/subscribe',
  getTotalPriceByBookingId: '/v1/order/total-price/${bookingId}',
  getUserOrdersTotalPrice: '/v1/order/retrieve/${bookingId}',
  getTranslations: '/v1/translations?language=${language}',
  getDishes: '/v1/menu/dish',
  getDrinks: '/v1/menu/drink',
} as const;
