export const UrlProvider = {
  baseUrl: 'http://localhost:3000/api',
  login: '/v1/auth/sign-in',
  user: '/v1/auth/user',
  register: '/v1/auth/register',
  getAvailableTables: '/v1/table/available/${date}',
  getBookingsByDate: '/v1/booking/active/${date}',
  getAvailableHours: '/v1/booking/available-hours',
  createBooking: '/v1/booking',
  updateBookingStatus: '/v1/booking/status/${bookingId}',
  getBooking: '/v1/booking/get/${bookingId}',
  getUserBookings: '/v1/booking/my-bookings',
  joinBooking: '/v1/booking/join',
  getAllMenus: '/v1/menu/available',
  getMenu: '/v1/menu/${menuId}',
} as const;
